// url=https://github.com/manolena/Beehive-Monitor/blob/main/text_strings.h
#ifndef TEXT_STRINGS_H
#define TEXT_STRINGS_H

#ifdef ARDUINO
#include <Arduino.h>
#endif

// Centralized text identifiers for all UI strings (EN/GR)
enum TextId
{
    TXT_NONE = 0,

    // MAIN MENU
    TXT_STATUS,
    TXT_TIME,
    TXT_MEASUREMENTS,
    TXT_WEATHER,
    TXT_CONNECTIVITY,
    TXT_DATA_SENDING,
    TXT_PROVISION,
    TXT_CALIBRATION,
    TXT_LANGUAGE,
    TXT_SD_INFO,
    TXT_BACK,

    // STATUS / COMMON
    TXT_FETCHING_WEATHER,
    TXT_WEATHER_NO_DATA,
    TXT_LAST_FETCH,
    TXT_PRESS_ANY,
    TXT_PRESS_SELECT,

    // PROVISION / KEY ENTRY
    TXT_ENTER_API_KEY,
    TXT_KEY_STORED,
    TXT_KEY_STORED_VERIFY,
    TXT_CANCELLED,
    TXT_ENTER_CITY,
    TXT_ENTER_COUNTRY,
    TXT_GEOCODE_SAVED,
    TXT_GEOCODE_FAILED,
    TXT_VERIFYING_KEY,

    // MEASUREMENTS SUBPAGE LABELS
    TXT_WEIGHT,
    TXT_T_INT,
    TXT_H_INT,
    TXT_T_EXT,
    TXT_H_EXT,
    TXT_PRESSURE,
    TXT_ACCEL,

    // CALIBRATION
    TXT_TARE,
    TXT_CALIBRATE_KNOWN,
    TXT_RAW_VALUE,
    TXT_SAVE_FACTOR,
    TXT_TARE_DONE,
    TXT_CALIBRATION_DONE,
    TXT_FACTOR_SAVED,
    TXT_TARE_PROMPT,
    TXT_PLACE_WEIGHT,
    TXT_MEASURING,
    TXT_SAVE_FAILED,
    TXT_NO_CALIBRATION,

    // NEW: Additional calibration strings
    TXT_CALIBRATE_READ_RAW,
    TXT_SEL_TO_SHOW_VALUE,
    TXT_RAW_LABEL,
    TXT_FACTOR_LABEL,
    TXT_OFFSET_LABEL,

    // CONNECTIVITY
    TXT_WIFI_CONNECTED,
    TXT_LTE_REGISTERED,
    TXT_NO_CONNECTIVITY,
    TXT_SSID,
    TXT_RSSI,
    TXT_MODE,
    TXT_MODE_LTE,
    TXT_MODE_WIFI,
    TXT_CHOOSE_NETWORK,
    TXT_UP_DOWN_SEL_OK,

    // SD
    TXT_SD_CARD_INFO,
    TXT_SD_OK,
    TXT_NO_CARD,

    // LANGUAGE
    TXT_LANGUAGE_EN,
    TXT_LANGUAGE_GR,

    // DATA SENDING
    TXT_INTERVAL_SELECT,
    TXT_UP_DOWN_CHANGE,
    TXT_SEL_SAVE_BACK_EXIT,
    TXT_SAVED,

    // TIME
    TXT_DATE_LABEL,
    TXT_TIME_LABEL,

    // WEATHER
    TXT_WEATHER_HEADER,
    TXT_LAT_LABEL,
    TXT_LON_LABEL,

    // STATUS
    TXT_BATTERY_LABEL,
    TXT_WEIGHT_KG,
    TXT_ACC_LABEL,

    // Small helpers
    TXT_BACK_SMALL,
    TXT_OK,
    TXT_ERROR,

    TXT_COUNT
};

const char* getTextEN(TextId id);
const char* getTextGR(TextId id);

#endif // TEXT_STRINGS_H
